set_project("CombatBusPhase1VOffline")
set_version("1.0.0")
set_languages("c11", "cxx20")
set_warnings("allextra", "error")

target("combatbus_phase1o_fixtures")
    set_kind("binary")
    add_files("../../src/CombatBusV3/CombatBusPrototype.cpp", "tests/CombatBusPrototypeTests.cpp")
    add_includedirs("include", "../../src/CombatBusV3")
    add_defines("IIF_COMBATBUS_OFFLINE_TESTING")

target("combatbus_iif_mock")
    set_kind("shared")
    add_files("../../src/CombatBusV3/CombatBusPrototype.cpp", "../../src/CombatBusV3/CombatBusCABI.cpp")
    add_includedirs("include", "tests", "../../src/CombatBusV3")
    add_defines("IIF_CB_HOST_EXPORTS", "IIF_CB_TEST_HOOKS", "IIF_CB_TEST_HOST_CONTROL",
        "IIF_COMBATBUS_OFFLINE_TESTING")

target("combatbus_production_contract")
    set_kind("shared")
    add_files("../../src/CombatBusV3/CombatBusPrototype.cpp", "../../src/CombatBusV3/CombatBusCABI.cpp")
    add_includedirs("../../src/CombatBusV3")
    add_defines("IIF_CB_HOST_EXPORTS", "IIF_CB_PRODUCTION_HOST")

target("combatbus_production_export_probe")
    set_kind("binary")
    add_files("tests/ProductionExportProbe.cpp")
    add_includedirs("../../src/CombatBusV3")

target("combatbus_test_provider")
    set_kind("shared")
    add_files("tests/MockProviderDll.cpp")
    add_includedirs("include", "../../src/CombatBusV3")
    add_defines("IIF_CB_TEST_HOST_CONTROL")

target("combatbus_test_provider_missing_export")
    set_kind("shared")
    set_basename("combatbus_test_provider_missing_export")
    add_files("tests/MockProviderDll.cpp")
    add_includedirs("include", "../../src/CombatBusV3")
    add_defines("IIF_CB_TEST_HOST_CONTROL")
    add_defines("COMBATBUS_TEST_OMIT_CALLBACK_SHUTDOWN_STATUS")

target("combatbus_cross_dll_host")
    set_kind("binary")
    add_files("tests/CrossDllHost.cpp", "tests/CAbiHeaderSmoke.c")
    add_includedirs("include", "tests", "../../src/CombatBusV3")
    add_defines("IIF_CB_TEST_HOST_CONTROL")

target("combatbus_startup_probe")
    set_kind("binary")
    add_files("tests/StartupProbe.cpp")
    add_includedirs("tests")
